server:
  port: 8080
  domain: ""
spring:
  datasource:
    url: jdbc:mysql://8.138.14.210:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: "******"

aliyun:
  ossBucket: "kdd-local"