services:
  service-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: service-client
    pull_policy: never
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  service-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: service-admin
    pull_policy: never
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
