services:
  service-client:
    image: service-client:dev
    container_name: service-client-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /home/jia/workspace/multi/multi-dev/service-client-logs:/app/logs
    ports:
      - "18881:8080"

  service-admin:
    image: service-admin:dev
    container_name: service-admin-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /home/jia/workspace/multi/multi-dev/service-admin-logs:/app/logs
    ports:
      - "18882:8080"
